# Generated by Django 3.1.3 on 2020-11-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="apply_link",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
