# Generated by Django 3.0.5 on 2020-06-15 14:50

from django.db import migrations, models

import blog.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=blog.models.get_upload_path
            ),
        ),
    ]
