# Generated by Django 3.0.3 on 2020-08-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="email",
        ),
    ]
