# Generated by Django 3.0.4 on 2020-04-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.CharField(default='www.google.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='title',
            field=models.CharField(default='k', max_length=20),
            preserve_default=False,
        ),
    ]
