# Generated by Django 3.0.5 on 2020-06-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscweb', '0003_auto_20200417_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.URLField(),
        ),
    ]
