# Generated by Django 3.0.5 on 2020-06-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscweb', '0004_auto_20200606_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
