# Generated by Django 3.0.5 on 2020-06-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscweb', '0005_auto_20200606_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.ImageField(height_field=133, upload_to='', width_field=133),
        ),
    ]
