# Generated by Django 3.0.5 on 2020-06-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscweb', '0009_auto_20200607_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.ImageField(upload_to='images/members/'),
        ),
    ]
