# Generated by Django 3.0.5 on 2020-06-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dscweb', '0011_heads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Heads',
            new_name='Head',
        ),
    ]
