# Generated by Django 3.1 on 2020-10-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competition_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='competition',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
    ]
